#!/bin/bash

feh --bg-scale ~/Pictures/everest.jpg &
xset -b &
xrdb ~/.Xresources &
LC_ALL=C parcellite &
dunst &
setxkbmap -option caps:escape
syndaemon -k -K -d -i 0.2 -R &
udiskie --tray & > /dev/null
nm-applet & > /dev/null
