#!/bin/bash

# desktop background
killall -q feh
feh --randomize --bg-max ~/images/* &

xset -b &
#xrdb ~/.Xresources &
#dunst &

# set CapsLock as escape
setxkbmap -option caps:escape
# disable Ctrl-s on terminal
stty -ixon
#udiskie --tray & > /dev/null
#nm-applet & > /dev/null

# clipboard daemon
killall -q greenclip
greenclip daemon &

