#!/bin/bash

#feh --randomize --bg-max ~/Pictures/sfondi/* &
xset -b &
#xrdb ~/.Xresources &
#LC_ALL=C parcellite &
#dunst &
setxkbmap -option caps:escape
#udiskie --tray & > /dev/null
#nm-applet & > /dev/null
